project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('textadventure/', include('textadventure.urls')),
]

textadventure/urls.py
from django.urls import path

from . import views

urlpatterns = [
        # Default, Station mit dem Namen "start"
        path('', views.station, name="station-default"),
        path('<str:name>', views.station, name="station"),
]

textadventure/models.py
from django.db import models

# Create your models here.


class Station(models.Model):
    '''
    Eine Station im Textadventure. Der Name ist eine sprechende ID,
    muss also eindeutig (unique) sein.
    '''
    name = models.CharField(max_length=50, unique=True)
    title = models.CharField(max_length=200)
    text = models.TextField()

    def __str__(self):
        return self.name


class Choice(models.Model):
    '''
    Eine Auswahloptin. Neben dem Text zur Beschreibung enthält Sie auch den 
    Verweis auf die nächste Station.
    '''
    station = models.ForeignKey(to=Station, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    next_station = models.ForeignKey(to=Station, on_delete=models.CASCADE, related_name="incoming_set")

    def __str__(self):
        return f"{self.text}: {self.next_station.name}" 

textadventure/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.

from . import models

print("Los geht es hier: http://localhost:8000/textadventure/start")

def station(request, name="start"):
    '''
    Hier wird die passende Station geholt und ausgegeben.
    Wird kein Name übergeben, dann wird die Station 'start' geholt.
    '''
    station = get_object_or_404(models.Station, name=name) 
    return render(request, "textadventure/station.html", {"station": station})

textadventure/templates/textadventure/station.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Textadventure</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  </head>
  <body>

    <div class="container mt-5">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{station.title}}</h5>
          <p class="card-text">{{station.text}}</p>
          {% for choice in station.choice_set.all %}
          <a href="{{choice.next_station.name}}" class="btn btn-primary">{{choice.text}}</a>
          {% endfor %}
        </div>
      </div>
    </div>


  </body>
</html>